version: "3.8"
services:
  node: 
    image: "node:20"
    environment:
      NODE_ENV: development
      DB_URL: mongodb://mongo/heycoach
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run compile && npm start"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    
